# 서비스 목록
services:

  # FastAPI 서비스
  api:
    build: ./api # ./api/Dockerfile 빌드
    ports:
      - "8000:8000"

    # 볼륨 마운트
    volumes:
      - ./static:/app/static:ro

    # 실행 시 동작할 명령어
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
